services:
  triton:
    image: nvcr.io/nvidia/tritonserver:24.03-py3
    command: tritonserver --model-repository=/models
    ports:
      - "8000:8000" # HTTP
      - "8001:8001" # gRPC
      - "8002:8002" # metrics
    volumes:
      - ./model_repository:/models:ro
